-- USER
INSERT INTO USER_ACCOUNT (NO, ID, PW, auth_level) VALUES(default, 'hahava','{noop}12345', 'ADMIN');
INSERT INTO USER_ACCOUNT (NO, ID, PW, auth_level) VALUES(default, 'heeman','{bcrtpt}$2a$10$rSneeSqiaEUq09mwm/Qm/eF3B7QeAZlMFlCEyMjg6bhiN93HN7oWK', 'NORMAL');
INSERT INTO USER_ACCOUNT (NO, ID, PW, auth_level) VALUES(default, 'mj', '{bcrtpt}$2a$10$QCYEaPSX6rRCXnLdaMXcUepjguaYCvDgoMZ0CAM1lCdP7CbNzHgqW', 'NORMAL');

-- PROFILE
INSERT INTO PROFILE (USER_ACCOUNT_NO, PHONE_NO, USER_NAME) VALUES ('1','0101111111', 'LEE');
INSERT INTO PROFILE (USER_ACCOUNT_NO, PHONE_NO, USER_NAME) VALUES ('2','0102222222', 'KIM');
INSERT INTO PROFILE (USER_ACCOUNT_NO, PHONE_NO, USER_NAME) VALUES ('3','0103333333', 'PARK');
